apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache
  labels:
    app: apache
    logstash-collect: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
      logstash-collect: "true"
  template:
    metadata:
      labels:
        app: apache
        logstash-collect: "true"
    spec:
      containers:
        - name: apache
          image: httpd:alpine3.14
          ports:
            - containerPort: 80
