apiVersion: v1
kind: Namespace
metadata:
  name: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache
  labels:
    app: apache
    logstash-collect: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
      logstash-collect: "true"
  template:
    metadata:
      labels:
        app: apache
        logstash-collect: "true"
    spec:
      containers:
        - name: apache
          image: httpd:alpine3.14
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: apache
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: apache
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegeta
  namespace: apache
  labels:
    app: vegeta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vegeta
  template:
    metadata:
      labels:
        app: vegeta
    spec:
      containers:
        - name: vegeta-200
          image: peterevans/vegeta:6.9.1
          command:
            - /bin/sh
            - -c
            - "while true; do echo 'GET http://apache' | vegeta attack -rate=$(tr -cd 0-9 </dev/urandom | head -c 2) -duration=30s | vegeta report; done"
        - name: vegeta-404
          image: peterevans/vegeta:6.9.1
          command:
            - /bin/sh
            - -c
            - "while true; do echo 'GET http://apache/test' | vegeta attack -rate=$(tr -cd 0-9 </dev/urandom | head -c 1) -duration=30s | vegeta report; done"
