controller:
  admissionWebhooks:
    enabled: true

  metrics:
    enabled: true

  service:
    enableHttp: false
    enableHttps: true

    ports:
      https: 443

    targetPorts:
      https: http

    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "name=${lb_name}"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "${acm_certificate_arn}"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"

  ingressClassResource:
    name: ${ingess_class_name}
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

tcp:
  ${logstash_beats_port}: "${logstash_namespace}/${logstash_service_name}:${logstash_beats_port}"
  ${graylog_beats_port}: "${graylog_namespace}/${graylog_service_name}:${graylog_beats_port}"
