controller:
  admissionWebhooks:
    enabled: true

  metrics:
    enabled: true

  ingressClassResource:
    name: ${ingess_class_name}
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

tcp:
  ${logstash_beats_port}: "${logstash_namespace}/${logstash_service_name}:${logstash_beats_port}"
  ${graylog_beats_port}: "${graylog_namespace}/${graylog_service_name}:${graylog_beats_port}"
